all: bubble hexa
	
bubble:
	gcc -g -c -o bubblesort.o lab3_bubblesort.c
	gcc -o bubblesort bubblesort.o

hexa:
	gcc -g -c -o hexaPrint.o hexaPrint.c
	gcc -o hexaPrint hexaPrint.o

clear:
	rm -f *.o bubblesort